fun main()
{
    print("Enter your name :- ")
    var a = readLine()
    print("Enter your Enrollment No :- ")
    var b = readLine()
    print("Enter your Branch :- ")
    var c = readLine()
    print("Enter your Class :- ")
    var d = readLine()
    print("Enter your Batch :- ")
    var e = readLine()
    print("Enter your College Name :- ")
    var f = readLine()
    print("Enter your University Name :- ")
    var g = readLine()
    print("Enter your Age :- ")
    var h = readLine()

    println("\n\nStudent name :- "+a)
    println("Student Enrollment No :- "+b)
    println("Student Branch :- "+c)
    println("Student Class :- "+d)
    println("Student Batch :- "+e)
    println("Student College Name :- "+f)
    println("Student University Name :- "+g)
    println("Student Age:- "+h)
}